mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
                  path("yoga/", include("yoga.urls")),
                  path("admin/", admin.site.urls),
                  path("", RedirectView.as_view(url="yoga/", permanent=True)),
                  path("tinymce/", include("tinymce.urls"))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/yoga/urls.py
from django.urls import path, include
from unicodedata import name

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('teachers/', views.teachers, name='teachers'),
    path('teachers/<int:teacher_id>', views.teacher, name='teacher-detail'),
    path('lessons/', views.LessonListView.as_view(), name='lessons'),
    path('lessons/<int:pk>', views.LessonDetailView.as_view(), name='lesson-detail'),
    path('search/', views.search, name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mylessons/', views.LoanedLessonsByUserListView.as_view(), name='my-lessons'),
    path('blog/', views.blog, name='blog-detail'),
    path('register/', views.register, name='register'),
    path('book/', views.booklesson, name='book-lesson'),
    path('gallery/', views.gallery, name='gallery-detail'),
]

mysite/yoga/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

from tinymce.models import HTMLField



class Type(models.Model):
    name = models.CharField('Title', max_length=200, help_text='Entry lesson title')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Type"
        verbose_name_plural = "Types"


class Lesson(models.Model):
    title = models.CharField('Title', max_length=200)
    teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True, related_name='lessons')
    summary = models.TextField('Description', max_length=1000, help_text='Short lesson description')
    lesson_type = models.ManyToManyField('Type', help_text='Please choose type of this lesson')
    cover = models.ImageField('Viršelis', upload_to='covers', null=True)
    price = models.IntegerField('Price', null=True)

    def display_type(self):
        return '; '.join([type.name for type in self.lesson_type.all()])

    display_type.short_description = 'Type'

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('lesson-detail', args=[str(self.id)])

    class Meta:
        verbose_name = "Lesson"
        verbose_name_plural = "Lessons"


class LessonInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique lesson code')
    lesson = models.ForeignKey('Lesson', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField('Will be available', null=True, blank=True)

    LOAN_STATUS = (
        ('p', 'Planning'),
        ('a', 'Not available'),
        ('b', 'You can book'),
        ('r', 'Reserved')
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='p',
        help_text='Status'
    )

    student = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']  # admin svetainės settingas, kaip rikiuojama

    def __str__(self):
        return f'{self.id} {self.lesson.title}'


class Teacher(models.Model):
    first_name = models.CharField('Name', max_length=100)
    last_name = models.CharField('Surname', max_length=100)
    description = HTMLField(default="cia turi buti pamokos aprasymas")

    def display_lessons(self):
        return ', '.join([lesson.title for lesson in self.lessons.all()][:3]) + "..."

    display_lessons.short_description = 'Lessons'

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('teacher-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Blog(models.Model):
    title = models.CharField('Title', max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Description', max_length=1000, help_text='Short description')
    cover = models.ImageField('Viršelis', upload_to='covers', null=True)

    def __str__(self):
        return self.title


class Gallery(models.Model):
    title = models.CharField('Title', max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    cover = models.ImageField('Viršelis', upload_to='covers', null=True)

    def __str__(self):
        return self.title

mysite/yoga/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Teacher, Lesson, LessonInstance, Blog, Gallery


def index(request):
    # count užklausos(queries)
    num_lessons = Lesson.objects.all().count()  # suskaičiuojam knygas
    num_instances = LessonInstance.objects.all().count()  # suskaičiuojam knygų kopijas

    # suskaičiuojam laisvas knygas(statusas g)
    num_instances_available = LessonInstance.objects.filter(status__exact="p").count()

    # suskaičiuojam autorius
    num_teachers = Teacher.objects.all().count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {  # šablono konteksto kintamasis
        'num_lessons': num_lessons,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_teachers': num_teachers,
        'num_visits': num_visits
    }

    # formuojam galutinį vaizdą iš šablono index.html ir duomenų
    # context žodyne(request - užklausa atėjusi iš kliento)
    return render(request, 'index.html', context=context)


def teachers(request):
    # authors = Author.objects.all()
    paginator = Paginator(Teacher.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_teachers = paginator.get_page(page_number)
    context = {
        'teachers': paged_teachers
    }
    return render(request, 'teachers.html', context=context)


def teacher(request, teacher_id):
    single_teacher = get_object_or_404(Teacher, pk=teacher_id)
    return render(request, 'teacher.html', {'teacher': single_teacher})


class LessonListView(generic.ListView):
    model = Lesson  # pagal modelio pav. autosukuriamas book_list kintamasis(visi objektai iš klasės) perduodamas į šabloną
    paginate_by = 3
    template_name = 'lesson_list.html'
    # context_object_name = 'my_book_list' galime pasikeisti automatinį konteksto kintamąjį(book_list) į custom pavadinimą


class LessonDetailView(generic.DetailView):
    model = Lesson  # šablonui autosukuriamas kintamas book
    template_name = 'lesson_detail_styled.html'


def search(request):
    query = request.GET.get("query")
    search_results = Lesson.objects.filter(
        Q(title__icontains=query) |
        Q(summary__icontains=query)
    )

    return render(request, "search.html", {"lessons": search_results, "query": query})


class LoanedLessonsByUserListView(LoginRequiredMixin, generic.ListView):
    model = LessonInstance
    template_name = "user_lessons.html"

    def get_queryset(self):
        # return LessonInstance.objects.filter(student=self.request.user).filter(status__exact='p').order_by("due_back")
        return LessonInstance.objects.filter(student=self.request.user).order_by("due_back")


def blog(request):
    paginator = Paginator(Blog.objects.all(), 5)
    page_number = request.GET.get('page')
    paged_blog = paginator.get_page(page_number)
    context = {
        'blog': paged_blog
    }
    return render(request, 'blog.html', context=context)


def gallery(request):
    paginator = Paginator(Gallery.objects.all(), 5)
    page_number = request.GET.get('page')
    paged_gallery = paginator.get_page(page_number)
    context = {
        'gallery': paged_gallery
    }
    return render(request, 'gallery.html', context=context)


@csrf_protect
def register(request):
    if request.method == "POST":
        # Pasiimam reiksmes is registracijos formos lauku
        username = request.POST["username"]
        email = request.POST["email"]
        password1 = request.POST["password"]
        password2 = request.POST["password2"]
        # ar sutampa ivesti passwordai
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f"User name {username} exist")
                return redirect("register")
            else:
                # ar nera tokio pacio emailo
                if User.objects.filter(email=email).exists():
                    messages.error(request, f"Emai {email} already exist")
                    return redirect("register")
                else:
                    # taskas kai viskas tvarkoje, patikrinimai praeiti, kuriam nauja useri
                    User.objects.create_user(username=username, email=email, password=password1)
                    messages.info(request, f"User {username} succsesfull registrated")
                    return redirect("login")
        else:
            messages.error(request, "Passwords not the same")
            return redirect("register")
    return render(request, "register.html")


@login_required(login_url='/yoga/accounts/login/', redirect_field_name='next')
def booklesson(request):
    # Logic for creating and saving a new book object
    # lessonID = request.POST["lessonID"]
    # print(lessonID)
    if request.method == "POST":
        lessonID = request.POST["lessonID"]
        print(lessonID)
        # les = Lesson.objects.filter(id=lessonID)
        lesObj = Lesson.objects.get(id=lessonID)
        studentObj = User.objects.get(username=request.user)
        # print(les)
        print(lesObj)
        print(request.user)
        # messages.info(request, lessonID)
        lessonInst = LessonInstance(lesson=lesObj, student=studentObj)
        lessonInst.save()
        return render(request, "book_lesson.html")
    else:
        messages.error(request, "Book lesson again please")
        return redirect('/yoga/lessons/')

mysite/yoga/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Yoga Online</title>
    {% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<!-- Navigation -->

<nav
        class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow"
>
    <div class="container">
        <a class="navbar-brand" href="#">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="16" height="16"
                 fill="currentColor"
                 class="bi bi-suit-heart"
                 viewBox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
            </svg>
            Yoga online!
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="16" height="16"
                 fill="currentColor"
                 class="bi bi-suit-heart"
                 viewBox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
            </svg>
        </a>
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lessons' %}">Lessons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers' %}">Teachers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog-detail' %}">Blog</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'gallery-detail' %}">Gallery</a>
                </li>
                {% if user.is_authenticated %}
                 <li class="nav-item"><a class="nav-link" href="{% url 'my-lessons'%}">My lessons</a></li>
                <li class="nav-item"><a class="nav-link" href="#">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">LOG OUT</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">LOG IN</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Register</a></li>
                {% endif %}
            </ul>

            <form
                    class="form-inline my-2 my-lg-0"
                    action="{% url 'search' %}"
                    method="get"
            >
                <input
                        class="form-control mr-sm-2"
                        type="search"
                        placeholder="Paieška"
                        aria-label="Search"
                        name="query"
                />
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
                    Search
                </button>
            </form>
        </div>
    </div>
</nav>
<div class="container">{% block content %}{% endblock %}</div>

<script
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"
></script>
<script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"
></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"
></script>
</body>
</html>

mysite/yoga/templates/blog.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h1 xmlns:border="http://www.w3.org/1999/xhtml">Blog</h1>
{% for blog_obj in blog %}
<div>
<p><b>
    {{blog_obj}}</b></p>
    <p>
    {% if blog_obj.cover %}
        <img src="{{ blog_obj.cover.url }}"  style="max-height:200px;width: auto;float: left;margin-right: 1.5em;">
    {% else %}
        <img src="{% static 'img/no-image.png' %}" class="blog-img-post">
    {% endif %}</p>
    <p>{{ blog_obj.content  }}</p>
    <br></br>
</div>
{% endfor %}

{% endblock %}

mysite/yoga/templates/book_lesson.html
{% extends "base.html" %}
{% block content %}
<h1> Book Lesson </h1>
<p>We will contact you </p>

{% endblock %}

mysite/yoga/templates/gallery.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h1 xmlns:border="http://www.w3.org/1999/xhtml">Gallery</h1>

{% for gallery_obj in gallery %}
<div>
<p>
    {{gallery_obj}}</p>
    {% if gallery_obj.cover %}
        <img src="{{ gallery_obj.cover.url }}"  style="width:350px">
    {% else %}
        <img src="{% static 'img/no-image.png' %}" class="gallery-img-post">
    {% endif %}
    <p>{{ gallery_obj.content  }}</p>
    <br></br>
</div>
{% endfor %}

{% endblock %}

mysite/yoga/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>YOGA EVERYWHERE!</h1>
<p><b>WELCOME TO YOGAONLINE!</b></p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/d-v5AUBkIpU" title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen></iframe>
<p>Please Choose the best lesson for you!</p>
<ul>
    <li>Lessons: {{ num_lessons }}</li>
    <li>Dates and prices: {{ num_instances }}</li>
    <li>Available lessons: {{ num_instances_available }}</li>
    <li>Teachers: {{ num_teachers }}</li>
</ul>
<p>NAMASTE, {{ user }}</p>
<p>You are visiting this page: {{ num_visits}} time</p>
{% endblock %}

mysite/yoga/templates/lesson_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ lesson.title }} </h1>
<p>Teacher: <a href="{% url 'teacher-detail' lesson.teacher.id %}">{{ lesson.teacher }}</a></p>
<p>Description: {{ lesson.summary }}  </p>
<!--<p>ISBN: {{ book.isbn }} </p>-->
<p>Type: {{ lesson.type.all|join:", " }}</p>

<h4>Description:</h4>
{% for lesson_inst_obj in lesson.lesson_instance_set.all %}
{% for eilute_obj in uzsakymas.uzsakymoeilute_set.all %}
<hr>
<p>{{ lesson_inst_obj.get_status_display }}</p>
<p>{{ lesson_inst_obj.due_back }}</p>
<p>{{ lesson_inst_obj.id }}</p>
{% endfor %}
{% endblock %}

mysite/yoga/templates/lesson_detail_styled.html
{% extends "base.html" %}
{% block content %}
<h1>{{ lesson.title }} </h1>
<p><strong>Teacher: </strong><a href="{% url 'teacher-detail' lesson.teacher.id %}">{{ lesson.teacher }}</a></p>
<p><strong>Description: </strong>{{ lesson.summary }} </p>
<!--<p><strong>ISBN: </strong>{{ book.isbn }} </p>-->
<p><strong>Type: </strong>{{ lesson.type.all|join:", " }}</p>

<h4>Choose the best time for you</h4>
{% for lesson_inst_obj in lesson.lessoninstance_set.all %}
<hr>

<p class="{% if lesson_inst_obj.status == 'b' %}text-success
{% elif lesson_inst_obj.status == 'p' %}text-danger
{% else %}text-warning
{% endif %}">{{ lesson_inst_obj.get_status_display }}</p>

{% if lesson_inst_obj.status != 'a' %}
<p>{{ lesson_inst_obj.due_back }}</p>
{% endif %}

<p class="text-muted">{{ lesson_inst_obj.id }}</p>
{% endfor %}
{% endblock %}

mysite/yoga/templates/lesson_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<h1>Lessons list</h1>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% if lesson_list %}
<div class="row">
    {% for lesson_obj in lesson_list %}
    <div class="col-md4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm" style="width: 14rem;">
            {% if lesson_obj.cover %}
                <img src="{{ lesson_obj.cover.url }}" class="card-img-top">
<!--            style="width: 300px;height:200px">-->
            {% else %}
                <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">{{ lesson_obj.teacher }}</h6>
                <p class="card-text"><a class="card-link" href="{{ lesson_obj.id }}">{{ lesson_obj.title }}</a></p>
                {% if lesson_obj.price %}
                   <h6 class="card-subtitle mb-2 text-muted">{{ lesson_obj.price }} €</h6>
                {% else %}
                   <h6 class="card-subtitle mb-2 text-muted">FREE</h6>
                {% endif %}
                <form action="{% url 'book-lesson' %}" method="post">
                {% csrf_token %}
                    <input type="hidden" id="lessonID" name="lessonID" value="{{ lesson_obj.id }}">
                    <input type="submit" value="Book Lesson">
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>It is no lessons </p>
{% endif %}
{% endblock %}

mysite/yoga/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="container register">
    <h3>Register</h3><br/>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ messages }}

        </div>
        {% endfor %}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">User name</label>
            <input name="username" type="text"
                   class="form-control" id="username"
                   aria-describedby="usernameHelp">
            <small
                id="usernameHelp" class="form-text text-muted">till 150 symblos.</small>
        </div>
        <div class="form-group"><label for="exampleInputEmail1">E-mail</label>
            <input name="email" type="email"
                   class="form-control"
                   id="exampleInputEmail1"
                   aria-describedby="emailHelp"><small
                id="emailHelp" class="form-text text-muted">We will not share with no one. We will not send spam.
            Needed to send for new password. </small></div>
        <div class="form-group"><label for="password">Password</label>
            <input name="password" type="password"
                   class="form-control" id="password"
                   aria-describedby="pwdHelp"><small
                id="pwdHelp" class="form-text text-muted">Needed at least 8 symbols. Cannot be only numbers</small></div>
        <div class="form-group"><label for="password2">Confirm password</label>
            <input name="password2"
                   type="password"
                   class="form-control"
                   id="password2"
                   aria-describedby="pwd2Help">
        </div>
        <button type="submit" class="btn btn-primary register-button">Register</button>
    </form>
    <p>You already have your account <a href="{% url 'login' %}?next=/library"><strong>LogIn</strong></a></p></div>

{% endblock %}

mysite/yoga/templates/search.html
{% extends "base.html" %}
{% block content %}
<h1>Search {{query}} results:</h1>
{% if lessons %}
<ul>
    {% for lesson_obj in lessons %}
        <li>
        <a href="{% url 'lesson-detail' lesson_obj.id %}">{{ lesson_obj.title }}</a>
            {{ lesson_obj.teacher }}
        </li>
    {% endfor %}
</ul>
{% else %}
<p>Not founded nothing.. </p>
{% endif %}
{% endblock %}

mysite/yoga/templates/teacher.html
{% extends "base.html" %}
{% block content %}
<div>
    <h4>{{ teacher.first_name }} {{ teacher.last_name }}</h4>
    <hr/>
    <p>{{ teacher.description | safe }}</p>
    <hr/>
    <h5>We have this {{ teacher }} lessons:</h5>
    <ul>
        {% for lesson_obj in teacher.lessons.all %}
        <li> {{ lesson_obj.title }}</li>
        {% endfor %}
    </ul>


</div>


{% endblock %}

mysite/yoga/templates/teachers.html
{% extends "base.html" %}
{% block content %}
<h1>Teachers</h1>
<p>Our teachers list of the lessons: </p>
{% for teacher_obj in teachers %}
<li><a href="{% url 'teacher-detail' teacher_obj.id  %}">
    {{teacher_obj}} </a></li>
{% endfor %}
<div class="container puslapiai">
    <nav aria-label="...">
        {% if teachers.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in teachers.paginator.page_range %}
                    {% if teachers.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

mysite/yoga/templates/user_lessons.html
{% extends "base.html" %}
{% block content %}
<h1>Your all chosen lessons:</h1>
{% if lessoninstance_list %}
<ul>
    {% for lessoninst_obj in lessoninstance_list %}
    <li class="{% if lessoninst_obj.is_overdue %}text-danger{% endif %}"><a
            href="{% url 'lesson-detail' lessoninst_obj.lesson.pk %}">{{ lessoninst_obj.lesson.title }}</a>
        {{ lessoninst_obj.due_back }}
    </li>
    <p>The status is {{ lessoninst_obj.get_status_display }} </p>
    {% endfor %}
</ul>
{% else %}
<p>At the moment you haven't booked any lessons!</p>
{% endif %}

{% endblock %}